vich_uploader:
    db_driver: orm

    mappings:
        company_logo:
             uri_prefix: /uploads/company_logos
             upload_destination: '%kernel.project_dir%/public/uploads/company_logos'
             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
